services:
  mysql-master:
    image: docker.io/bitnami/mysql:latest
    ports:
      - '127.0.0.1:33306:3306'
#    volumes:
#      - ./my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
#      - 'mysql_master_data:/bitnami/mysql/data'
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=my_repl_password

      - MYSQL_DATABASE=my_database

      - MYSQL_AUTHENTICATION_PLUGIN=caching_sha2_password
      - MYSQL_USER=master_user
      - MYSQL_PASSWORD=master_password

      - MYSQL_ROOT_PASSWORD=my_root_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  mysql-slave:
    image: docker.io/bitnami/mysql:latest
    # volumes:
    #   - ./slave_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
    ports:
      - '127.0.0.1:33307:3306'
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=my_repl_password
      - MYSQL_REPLICATION_SLAVE_DUMP=false

      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_ROOT_PASSWORD=my_root_password
      - MYSQL_MASTER_PORT_NUMBER=3306
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

#volumes:
#  mysql_master_data:
#    driver: local
